Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var react_2 = require("@storybook/react");
var Container_1 = require("./Container");
var Content_1 = require("../elements/Content");
var Footer_1 = require("./Footer");
var Hero_1 = require("./Hero");
var Notification_1 = require("../elements/Notification");
var Title_1 = require("../elements/Title");
var Subtitle_1 = require("../elements/Subtitle");
react_2.storiesOf('Layout', module)
    .add('Container', function () { return (react_1.default.createElement(react_1.Fragment, null,
    react_1.default.createElement(Container_1.default, null,
        react_1.default.createElement(Notification_1.default, null,
            "This container is ",
            react_1.default.createElement("strong", null, "centered"),
            " on desktop.")),
    react_1.default.createElement(Container_1.default, { isFluid: true },
        react_1.default.createElement(Notification_1.default, null,
            "This container is ",
            react_1.default.createElement("strong", null, "fluid"),
            ": it will have a 32px gap on either side, on any viewport size.")),
    react_1.default.createElement(Container_1.default, { isWidescreen: true },
        react_1.default.createElement(Notification_1.default, null,
            "This container is ",
            react_1.default.createElement("strong", null, "fluid"),
            ": it will have a 32px gap on either side, on any viewport size.")),
    react_1.default.createElement(Container_1.default, { isFullhd: true },
        react_1.default.createElement(Notification_1.default, null,
            "This container is ",
            react_1.default.createElement("strong", null, "fullwidth"),
            " ",
            react_1.default.createElement("em", null, "until"),
            " the ",
            react_1.default.createElement("code", null, "$widescreen"),
            " breakpoint.")))); })
    .add('Hero', function () { return (react_1.default.createElement(react_1.Fragment, null,
    react_1.default.createElement(Hero_1.default, null,
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "Hero title"),
                react_1.default.createElement(Subtitle_1.default, null, "Hero subtitle")))),
    react_1.default.createElement(Hero_1.default, { isPrimary: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "isPrimary title"),
                react_1.default.createElement(Subtitle_1.default, null, "isPrimary subtitle")))),
    react_1.default.createElement(Hero_1.default, { isInfo: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "isInfo title"),
                react_1.default.createElement(Subtitle_1.default, null, "isInfo subtitle")))),
    react_1.default.createElement(Hero_1.default, { isSuccess: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "isSuccess title"),
                react_1.default.createElement(Subtitle_1.default, null, "isSuccess subtitle")))),
    react_1.default.createElement(Hero_1.default, { isWarning: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "Warning title"),
                react_1.default.createElement(Subtitle_1.default, null, "Warning subtitle")))),
    react_1.default.createElement(Hero_1.default, { isDanger: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "Danger title"),
                react_1.default.createElement(Subtitle_1.default, null, "Danger subtitle")))),
    react_1.default.createElement(Hero_1.default, { isLight: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "isLight title"),
                react_1.default.createElement(Subtitle_1.default, null, "isLight subtitle")))),
    react_1.default.createElement(Hero_1.default, { isDark: true },
        react_1.default.createElement(Hero_1.default.Body, null,
            react_1.default.createElement(Container_1.default, null,
                react_1.default.createElement(Title_1.default, null, "Dark title"),
                react_1.default.createElement(Subtitle_1.default, null, "Dark subtitle")))))); })
    .add('Footer', function () { return (react_1.default.createElement(Footer_1.default, null,
    react_1.default.createElement(Content_1.default, { hasTextCentered: true },
        react_1.default.createElement("p", null,
            react_1.default.createElement("strong", null, "Trunx"),
            " by ",
            react_1.default.createElement("a", { href: 'http://g14n.info' }, "Gianluca Casati"),
            ". The source code is licensed ",
            react_1.default.createElement("a", { href: 'http://g14n.info/mit-license' }, "MIT"),
            ".")))); });
