import { ClassNamesArg, classNames } from './classNames.js'
import _BulmaClassName from './bulmaClassNames.js'

// File bulmaClassNames.ts is generated by `generate_BulmaClassName_type` npm script.
// Bulma supports FontAwesome icons, there is .fa class that is not part of Bulma.
export type BulmaClassName = Exclude<_BulmaClassName, 'fa'>

export const bulma = (...args: ClassNamesArg<BulmaClassName>[]) => classNames<BulmaClassName>(...args)
